# alpine
FROM php:8.2-fpm

ENV PS1="\u@\h:\w\\$ "

RUN apt-get update \
    && apt-get install -y \
        bash \
        zip \
        unzip \
        linux-headers-generic \
        default-mysql-client \
        libmariadb-dev \
    && rm -rf /var/lib/apt/lists/*

# PHP extensions
RUN docker-php-ext-install opcache pdo_mysql mysqli
RUN docker-php-ext-enable opcache
RUN pecl install excimer

RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN rm -rf /var/cache/apk/*

CMD ["php-fpm", "--nodaemonize"]
