services:
  reverse-proxy:
    image: traefik:v3.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: opale_nginx
    volumes:
      - ./infra/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=80"
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.dev
    container_name: opale_php
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
    networks:
      - app-network

  db:
    image: mariadb:lts
    container_name: opale_mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ./infra/mariadb-data:/var/lib/mariadb
    ports:
      - 3306:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
